const BRAND_LOGOS: Record<string, string> = {
  Acura: "acura-logo.svg",
  "Alfa Romeo": "alfa-romeo-logo.svg",
  Alpine: "alpine-logo.svg",
  "Aston Martin": "aston-martin-logo.svg",
  Audi: "audi-logo.svg",
  Bentley: "bentley-logo.svg",
  BMW: "bmw-logo.svg",
  Buick: "buick-logo.png",
  Cadillac: "cadillac-logo.png",
  Chevrolet: "chevrolet-logo.png",
  Chrysler: "chrysler-logo.svg",
  Daihatsu: "daihatsu-logo.svg",
  Dodge: "dodge-logo.png",
  Ferrari: "ferrari-logo.svg",
  Fiat: "fiat-logo.svg",
  Ford: "ford-logo.png",
  GMC: "gmc-logo.png",
  Honda: "honda-logo.png",
  Infiniti: "infiniti-logo.svg",
  Isuzu: "isuzu-logo.svg",
  Jaguar: "jaguar-logo.svg",
  Jeep: "jeep-logo.svg",
  Koenigsegg: "koenigsegg-logo.svg",
  Lamborghini: "lamborghini-logo.png",
  "Land Rover": "land-rover-logo.svg",
  Lexus: "lexus-logo.png",
  Lincoln: "lincoln-logo.svg",
  Lotus: "lotus-logo.svg",
  "Lucid Motors": "lucid-logo.png",
  Maserati: "maserati-logo.png",
  Mazda: "mazda-logo.svg",
  McLaren: "mclaren-logo.svg",
  "Mercedes-Benz": "mercedes-benz-logo.svg",
  MINI: "mini-logo.svg",
  Mitsubishi: "mitsubishi-logo.svg",
  Mitsuoka: "mitsuoka-logo.png",
  Nissan: "nissan-logo.svg",
  Opel: "opel-logo.svg",
  Pagani: "pagani-logo.png",
  Peugeot: "peugeot-logo.svg",
  Polestar: "polestar-logo.png",
  Porsche: "porsche-logo.svg",
  Ram: "ram-logo.svg",
  Renault: "renault-logo.svg",
  Rimac: "rimac-logo.png",
  Rivian: "rivian-logo.svg",
  "Rolls-Royce": "rolls-royce-logo.svg",
  Subaru: "subaru-logo.png",
  Suzuki: "suzuki-logo.svg",
  Tesla: "tesla-logo.svg",
  Toyota: "toyota-logo.svg",
  Volkswagen: "volkswagen-logo.svg",
  Volvo: "volvo-logo.svg",
};

export function getBrandLogoPath(brandName: string) {
  const filename = BRAND_LOGOS[brandName];

  return filename ? `/brand-logos/${filename}` : null;
}
